### ISSUE TITLE
Jitsi strange room names

### ISSUE THREAD

**Issue by rbdevr** [seansackowitz/mattermost-plugin-jitsi#30]
Why the strange room names? Why not use the current channel name as room in jitsi?

**Comment by seansackowitz** [comment]
It uses "strange" room names because if you are using a public jitsi server such as https://meet.jit.si, then you are highly likely to run into other people's meetings, unless you use something pseudo random. So, I took a similar algorithm to what meet.jit.si uses to generate room names, and used it here.
There is consideration about adding additional room name generation types, so if you have a suggestion as to how to allow a mattermost admin to toggle between them on a mattermost config level, or even better, a pull request to do so, that would be wonderful. This discussion is on issue #22 however.
